// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Facts {
	
	
	public partial class SignupPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm SignUpForm;
		
		protected System.Web.UI.WebControls.TextBox EmailField;
		
		protected System.Web.UI.WebControls.Label EmailStatusLabel;
		
		protected System.Web.UI.WebControls.TextBox NameField;
		
		protected System.Web.UI.WebControls.Label NameStatusLabel;
		
		protected System.Web.UI.WebControls.TextBox PasswordField;
		
		protected System.Web.UI.WebControls.Label PasswordStatusLabel;
		
		protected System.Web.UI.WebControls.TextBox PasswordConfirmField;
		
		protected System.Web.UI.WebControls.Label PasswordConfirmStatusLabel;
		
		protected System.Web.UI.WebControls.Button SignUpButton;
	}
}
