// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Facts {
	
	
	public partial class MessageSubTree {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dSubroot;
		
		protected System.Web.UI.WebControls.Button bVoteUp;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dVotesScore;
		
		protected System.Web.UI.WebControls.Button bVoteDown;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dRating;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor aAuthor;
		
		protected System.Web.UI.WebControls.Label lCreated;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor aSelfLink;
		
		protected System.Web.UI.HtmlControls.HtmlButton bOpenReplyForm;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dText;
	}
}
