// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Facts {
	
	
	public partial class ReplyForm {
		
		protected System.Web.UI.WebControls.HiddenField activeMessageId;
		
		protected System.Web.UI.WebControls.RadioButtonList rblStatementDirection;
		
		protected System.Web.UI.WebControls.Button Reply;
		
		protected System.Web.UI.WebControls.TextBox Statement;
	}
}
