// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Facts {
	
	
	public partial class UserPage {
		
		protected System.Web.UI.HtmlControls.HtmlTableCell Id;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell Created;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell Name;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell MessageCount;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell Reputation;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell ActionPoints;
	}
}
