// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Facts {
	
	
	public partial class ThreadPage {
		
		protected System.Web.UI.WebControls.Content ThreadPageContent;
		
		protected System.Web.UI.HtmlControls.HtmlForm MessagesForm;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dMessages;
		
		protected Facts.ReplyForm ReplyForm;
	}
}
